<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>scc</string>
		<string>sch</string>
	</array>
	<key>name</key>
	<string>ScummC</string>
	<key>comment</key>
	<string>https://github.com/idleberg/ScummC-Sublime-Text</string>
	<key>scopeName</key>
	<string>source.scummc</string>
	<key>uuid</key>
	<string>e681b761-41da-4c79-a69b-04f6790f9517</string>
</dict>
</plist>
